document.write('	<div id="header"><!-- header -->');
document.write('		<div class="header_inner">');
document.write('			<h1 class="fl"><a href="../lms_0002.html" class="logo">EZ Learning</a></h1>');
document.write('			<div class="fr">');
document.write('				<div class="header_top">');
document.write('					<dl class="lst_util">');
document.write('						<dt class="blind">로그인 정보</dt>');
document.write('						<!-- dd class="first"><span class="ico ico_bell"></span> 강의신청 <span class="bg_rnd">99<span class="bg_redrnd lft"></span><span class="bg_redrnd rgt"></span></span></dd -->');
document.write('						<dd class="first"><span class="clr_gray4">박장용</span>님 안녕하세요 <a href="#" class="btn gray v14 ml5">로그아웃</a></dd>');
document.write('					</dl>');
document.write('					<div class="group_mainsrch">');
document.write('						<label for="usearch" class="plabel usearch">search</label><input type="text" id="usearch" title="검색어 입력"><a href="comm/lms_srch.html" class="btn_mainsrch"><span class="ico ico_retrieval">검색</span></a>');
document.write('						<div class="group_best_srch">');
document.write('							<div class="group_bestsrch_inner">');
document.write('								<h3>인기 검색어</h3>');
document.write('								<ul>');
document.write('									<li><a href="#">탄소 경영</a>,</li>');
document.write('									<li><a href="#">손자병법</a>,</li>');
document.write('									<li><a href="#">기초 회계</a>,</li>');
document.write('									<li><a href="#">유통마케팅</a>,</li>');
document.write('									<li><a href="#">프로직장</a></li>');
document.write('								</ul>');
document.write('							</div>');
document.write('							<div class="group_bestsrch_foot"><a href="#" class="btn_best_close">인기검색어 닫기</a></div>');
document.write('						</div>');
document.write('					</div>');
document.write('				</div>');
document.write('				<div id="gnb" class="group_gnb">');
document.write('					<h2 class="blind">메인메뉴</h2>');	
document.write('					<ul class="lst_gnb">');
document.write('						<li>');
document.write('							<a href="#none">수강신청</a>');
document.write('							<span class="ico_mainarrow v1"></span>');
document.write('							<div class="gnb_bgbox">');						
document.write('								<ul class="lst_gnb_depth2 v1">');
document.write('									<li><a href="#"><span class="m_ico m1"></span>과정검색</a></li>');
document.write('									<li><a href="#"><span class="m_ico m2"></span>수강신청 확인&frasl;취소</a></li>');
document.write('									<li><a href="#"><span class="m_ico m21"></span>사외과정학점신청</a></li>');
document.write('								</ul>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li class="on">');
document.write('							<a href="#none">강의실</a>');
document.write('							<span class="ico_mainarrow v2"></span>');
document.write('							<div class="gnb_bgbox">');								
document.write('								<ul class="lst_gnb_depth2 v2">');
document.write('									<li><a href="../lectureroom/lms_0201.html" class="on"><span class="m_ico m3"></span>학습중인 과정</a></li>');
document.write('									<li><a href="#"><span class="m_ico m4"></span>교육이력</a></li>');
document.write('									<li><a href="#"><span class="m_ico m5"></span>관심과정</a></li>');
document.write('									<li><a href="#"><span class="m_ico m22"></span>내가쓴글</a></li>');
document.write('									<li><a href="#"><span class="m_ico m6"></span>나의정보</a></li>');
document.write('								</ul>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li>');
document.write('							<a href="#none">교육안내</a>');
document.write('							<span class="ico_mainarrow v3"></span>');	
document.write('							<div class="gnb_bgbox">');								
document.write('								<ul class="lst_gnb_depth2 v3">');
document.write('									<li><a href="#"><span class="m_ico m7"></span>그룹교육체계</a></li>');
document.write('									<li><a href="#"><span class="m_ico m8"></span>고용보험환급제도</a></li>');
document.write('									<li><a href="#"><span class="m_ico m9"></span>그룹학점제</a></li>');
document.write('									<li><a href="#"><span class="m_ico m10"></span>톡톡맘</a></li>');
document.write('									<li><a href="#"><span class="m_ico m11"></span>직무자격인증제도</a></li>');
document.write('									<li><a href="#"><span class="m_ico m12"></span>간부승진제도</a></li>');
document.write('									<li><a href="#"><span class="m_ico m13"></span>롯데어학인증평가</a></li>');
document.write('								</ul>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li>');
document.write('							<a href="#none">고객센터</a>');
document.write('							<span class="ico_mainarrow v4"></span>');	
document.write('							<div class="gnb_bgbox">');							
document.write('								<ul class="lst_gnb_depth2 v4">');
document.write('								<li><a href="#"><span class="m_ico m14"></span>공지사항</a></li>');
document.write('									<li><a href="#"><span class="m_ico m15"></span>Q&amp;A</a></li>');
document.write('								<li><a href="#"><span class="m_ico m16"></span>FAQ</a></li>');
document.write('								<li><a href="#"><span class="m_ico m17"></span>원격지원서비스</a></li>');
document.write('									<li><a href="#"><span class="m_ico m23"></span>사이트이용메뉴얼</a></li>');
document.write('									<li><a href="#"><span class="m_ico m24"></span>필수프로그램다운로드</a></li>');
document.write('								</ul>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li>');
document.write('							<a href="#none">인재개발원 소개</a>');
document.write('							<span class="ico_mainarrow v5"></span>');		
document.write('							<div class="gnb_bgbox">');					
document.write('								<ul class="lst_gnb_depth2 v5">');
document.write('									<li><a href="#"><span class="m_ico m18"></span>연수원안내</a></li>');
document.write('									<li><a href="#"><span class="m_ico m19"></span>원장인사말</a></li>');
document.write('									<li><a href="#"><span class="m_ico m20"></span>ebook 자료실</a></li>');
document.write('								</ul>');
document.write('							</div>');					
document.write('						</li>');
document.write('					</ul>');
document.write('				</div>');
document.write('			</div>');
document.write('		</div>');
document.write('		<span class="bg_white_cnt"></span>');
document.write('		<span class="bg_white_lft"></span>');
document.write('		<span class="bg_white_rgt"></span>');
document.write('	</div><!-- //header -->');